{
 "title": "PRODUCCIÓN TEMPERAS Y VINILOS",
 "time": { "from": "2023-09-12T12:00:00.000Z", "to": "2025-11-20T12:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "maquina", "query": "SELECT nombre FROM Maquinas;\n" },
   {
    "name": "operario",
    "query": "SELECT nombre FROM Operarios;\n"
   },
   {
    "name": "anio",
    "query": "SELECT DISTINCT año FROM registrosproduccion ORDER BY año;\n"
   },
   {
    "name": "mes",
    "query": "SELECT DISTINCT mes FROM RegistrosProduccion ORDER BY \n    CASE LOWER(mes)\n        WHEN 'enero' THEN 1 WHEN 'febrero' THEN 2 WHEN 'marzo' THEN 3\n        WHEN 'abril' THEN 4 WHEN 'mayo' THEN 5 WHEN 'junio' THEN 6\n        WHEN 'julio' THEN 7 WHEN 'agosto' THEN 8 WHEN 'septiembre' THEN 9\n        WHEN 'octubre' THEN 10 WHEN 'noviembre' THEN 11 WHEN 'diciembre' THEN 12\n    END;"
   }
  ]
 },
 "panels": [
  {
   "title": "Producción total por mes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n    TO_DATE(año || '-' || \r\n        CASE LOWER(mes)\r\n            WHEN 'enero' THEN '01'\r\n            WHEN 'febrero' THEN '02'\r\n            WHEN 'marzo' THEN '03'\r\n            WHEN 'abril' THEN '04'\r\n            WHEN 'mayo' THEN '05'\r\n            WHEN 'junio' THEN '06'\r\n            WHEN 'julio' THEN '07'\r\n            WHEN 'agosto' THEN '08'\r\n            WHEN 'septiembre' THEN '09'\r\n            WHEN 'octubre' THEN '10'\r\n            WHEN 'noviembre' THEN '11'\r\n            WHEN 'diciembre' THEN '12'\r\n        END\r\n        || '-01', 'YYYY-MM-DD'\r\n    ) AS fecha_mes,\r\n    SUM(pacas_producidas) AS total_pacas\r\nFROM RegistrosProduccion\r\nGROUP BY año, mes\r\nORDER BY año, fecha_mes;\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "<center>\r\nREGISTRO DE PRODUCCIÓN\r\n</center>"
   }
  },
  {
   "title": "Producción total de pacas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT SUM(pacas_producidas) FROM registrosproduccion;"
    }
   ]
  },
  {
   "title": "Indicador de eficiencia global",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  ROUND(\r\n    (SUM(horas_trabajadas) / NULLIF(SUM(horas_trabajadas) + SUM(horas_no_trabajadas), 0)) * 100,\r\n    2\r\n  ) AS eficiencia_porcentual\r\nFROM registrosproduccion;"
    }
   ]
  },
  {
   "title": "Monitoreo Producción Diaria",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n    fecha,\r\n    SUM(pacas_producidas) AS total_pacas\r\nFROM RegistrosProduccion\r\nGROUP BY fecha\r\nORDER BY fecha;"
    }
   ]
  },
  {
   "title": "Producción por operario",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n    o.nombre AS operario,\r\n    SUM(rp.pacas_producidas) AS total_pacas\r\nFROM RegistrosProduccion rp\r\nJOIN Operarios o ON rp.operario_id = o.id_operario\r\nGROUP BY o.nombre\r\nORDER BY total_pacas DESC;"
    }
   ]
  },
  {
   "title": "Pacas producidas por maquina",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n    m.nombre AS maquina,\r\n    SUM(rp.pacas_producidas) AS total_pacas\r\nFROM RegistrosProduccion rp\r\nJOIN Maquinas m ON rp.maquina_id = m.id_maquina\r\nGROUP BY m.nombre\r\nORDER BY total_pacas DESC;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "<center>\r\n  DETALLES PAROS DE PRODUCCIÓN\r\n</center> "
   }
  },
  {
   "title": "Horas trabajadas vs No trabajadas (por máquina)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  m.nombre AS maquina,\r\n  SUM(r.horas_trabajadas) AS horas_trabajadas,\r\n  SUM(r.horas_no_trabajadas) AS horas_no_trabajadas\r\nFROM registrosproduccion r\r\nJOIN maquinas m ON r.maquina_id = m.id_maquina\r\nGROUP BY m.nombre\r\nORDER BY m.nombre;"
    }
   ]
  },
  {
   "title": "Paros por área involucrada",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n    area_involucrada,\r\n    SUM(horas_paro) AS total_horas\r\nFROM DetalleParosProduccion\r\nGROUP BY area_involucrada\r\nORDER BY total_horas DESC;\r\n"
    }
   ]
  },
  {
   "title": "Detalle de los últimos paros",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  r.fecha,\r\n  m.nombre AS maquina,\r\n  d.codigo_paro,\r\n  d.horas_paro,\r\n  d.area_involucrada,\r\n  d.personal_involucrado,\r\n  d.observaciones_paro\r\nFROM detalleparosproduccion d\r\nJOIN registrosproduccion r ON d.registro_id = r.id_registro\r\nJOIN maquinas m ON r.maquina_id = m.id_maquina\r\nORDER BY r.fecha DESC\r\nLIMIT 20;\r\n"
    }
   ]
  }
 ]
}